apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.serviceName }}  # Tên hợp lệ (không có dấu gạch nối cuối)
  labels:
    app: {{ .Release.Name }}-{{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.serviceName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.service.type }}
